<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DcimCloudSync</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>

    <!-- Enable XAML source generation for faster build times and improved performance.
         This generates C# code from XAML at compile time instead of runtime inflation.
         To disable, remove this line.
         For individual files, you can override by setting Inflator metadata:
           <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
           <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
    <MauiXamlInflator>SourceGen</MauiXamlInflator>
    <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>

    <!-- Display name -->
    <ApplicationTitle>Android DCIM Cloud Sync</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId>io.github.f2calv.androiddcimcloudsync</ApplicationId>

    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#17171a" />

    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#17171a" BaseSize="128,128" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Microsoft.Maui.Controls" />
  </ItemGroup>
</Project>
